// <auto-generated />
using System;
using NostedServicePro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NostedServicePro.Migrations
{
    [DbContext(typeof(ServiceProDbContex))]
    [Migration("20231024133831_oppdatertservicetabell2")]
    partial class oppdatertservicetabell2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Bruker", b =>
                {
                    b.Property<int>("BrukerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BrukerNavn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Epostadresse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Passord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BrukerId");

                    b.ToTable("Brukere");
                });

            modelBuilder.Entity("ServiceOrdre", b =>
                {
                    b.Property<int>("OrdreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AvtaltKommentar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Avtaltferdigstillingsdato")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("AvtaltleveringsDato")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BremsekraftKn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bremser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BremsesylingerSkiftTelninger")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClutchLameller")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HydraulikkSylinderLekkasje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InternKommentar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KilleKjedehjul")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kjedestrammer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kundeepost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kundenavn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kundetlf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LagerTrommel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LedningsnettVinsj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PTOOpplagring")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlnlonLager")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Problembeskrivelse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ProduktmottattDato")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Produkttypevinsj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Registreringsdato")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RingsyllingerSkiftTelnlnger")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Serienummervinsj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkTestKnappekasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkTestRadio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SkiftOljeGirboks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SkiftOljeTank")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SlangerSkaderLekkasje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TestHydraulikkblokk")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TestVinsjAlleFunksjoner")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrekkraftKn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Wire")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("XXBar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ÅrsmodellVinsj")
                        .HasColumnType("int");

                    b.HasKey("OrdreID");

                    b.ToTable("service");
                });
#pragma warning restore 612, 618
        }
    }
}
